name: authentication
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.4+2
  google_sign_in: ^5.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1


flutter:

 